---
- name: "Set hostname to {{ hostname }}"
  win_hostname:
    name: "{{ hostname }}"
  register: res

- name: "Set timezone to {{ timezone }}" 
  win_timezone:
    timezone: "{{ timezone }}"

- name: Disable Shutdown Button from Windows Start
  win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer
    name: NoClose
    data: '1'
    type: dword
    state: "{{ 'present' if shutdown_button_disable else 'absent' }}"
  tags:
    - shutdown_button 
    - basic


- name: Disable Shutdown Button from Windows login screen
  win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    name: shutdownwithoutlogon
    data: "{{ '0' if shutdown_button_disable else '1' }}"
    type: dword
  tags:
    - shutdown_button 
    - basic


- name: Reboot
  win_reboot:
      reboot_timeout_sec: 120
      connect_timeout: 120
  ignore_errors: yes
  when: res.reboot_required